const meuNome = "luis";
const idade = 58;
const altura = 1.85;
const massa = 75;
const cidade = "São josé dos pinhais";
console.log(meuNome);
console.log(idade);
console.log(altura);
console.log(massa);
console.log(cidade);